config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  resources :tournaments, only: %i[index new create edit show update destroy] do
    collection do
      post :import
    end
    resources :rounds, only: %i[index show create destroy]
    resources :players, only: %i[index update destroy]
  end
  resources :rounds do
    resources :players do
      get :pair, on: :collection
    end
    resources :games
  end
  resources :players do
    member do
      get :round_status
    end
    resources :games
  end
  resources :results, only: %i[update]

  resources :tournament_registrations, only: %i[create update]

  get "tournaments/:tournament_id/standings",
  to: "standings#index", as: :tournament_standings
end

app/models/tournament.rb
# == Schema Information
#
# Table name: tournaments
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  location   :string           not null
#  begin_date :date             not null
#  end_date   :date             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Tournament < ApplicationRecord
  belongs_to :user, required: false
  has_many :rounds, dependent: :destroy
  has_many :tournament_registrations
  has_many :players, through: :tournament_registrations
  has_many :games, through: :rounds
  validates :name, presence: true,
                   uniqueness: {
                     scope: :begin_date,
                     message: "Should only happen once per year",
                   }
  validates :location, presence: true
  validates :begin_date, presence: true
  validates :end_date, presence: true
  attr_accessor :number_of_rounds
end

app/models/tournament/import.rb
require "csv"
require "aga_number"
class Tournament
  class Import
    include ActiveModel::Model
    attr_accessor :file, :tournament_count, :player_count

    def process!
      tournament_count = 0
      player_count = 0
      tr_count = 0
      players = []
      # import = WildApricotImport.new
      CSV.foreach(file.path, headers: true) do |row|
        if tournament_count.zero?
          @tournament = Tournament.new(
            name: row["Event title"],
            location: row["Event location"],
            begin_date: row["Start date"],
            end_date: row["End date"] || row["Start date"],
            number_of_rounds: 4,
          )
          if @tournament.save
          else
            errors.add(
              :base,
              "Failed to save tournament. Line #{$.} -
              #{@tournament.errors.full_messages.join(',')}",
            )
          end
          tournament_count += 1
        end
        player = Player.where(email: row["Email"]).first_or_initialize
        player.assign_attributes(
          first_name: row["First name"],
          last_name: row["Last name"],
          rank: row["Tournament Entry Rank"] || "30 kyu",
          aga_number: row["AGA ID"] || AgaNumber.auto_assign!,
          rating: 0,
          chapter_affiliation: "XX",
          state: "XX",
          phone: row["Phone"],
          zip: row["Zip"],
        )
        if player.save
          players << player
          player_count += 1
        else
          errors.add(
            :base,
            "Failed to save player on line #{$.} -
             #{player.errors.full_messages.join(',')}",
          )
        end
      end
      players.each do |player|
        tr = TournamentRegistration.new(player_id: player.id, tournament_id: @tournament.id, status: "preliminary")
        if tr.save
          tr_count += 1
        else
          errors.add(
            :base,
            "Failed to create registration for #{player.email}",
          )
        end
      end
    end

    def save
      process!
      errors.none?
    end
  end
end

app/models/tournament/rating_from_rank.rb
class RatingFromRank
  attr_accessor :rank, :rating

  def calculate!(rank)
    category = rank.last(3)
    floated_rating = rank.to_i + rand
    formated_rating = "%0.05f" % floated_rating

    imitation_aga_rating = BigDecimal(formated_rating)
    case category
    when "kyu"
      - imitation_aga_rating
    when "dan"
      imitation_aga_rating
    end
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: %i[show edit update destroy]

  def index
    @tournaments = Tournament.order(created_at: :desc)
    @import = Tournament::Import.new
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)
    @tournament.user_id = current_user.id

    if @tournament.save
      @rounds = []
      params[:tournament][:number_of_rounds].to_i.times do |number|
        @rounds << Round.new(number: number + 1, tournament: @tournament)
      end

      if @rounds.each(&:save)
        redirect_to root_path, notice: "New tournament created"
      else
        render :new, notice: "There was an error."
      end

    else
      render :new, notice: "There was an error."
    end
  end

  def show
    @player = Player.find_by(id: params[:player_id]) || Player.new
    @tournament = Tournament.find(params[:id])
    @tournament_registration = TournamentRegistration.find_by(
      player_id: @player.id,
      tournament_id: @tournament.id,
    ) || TournamentRegistration.new

    all_players = Player.all
    @players = Player.joins(
      :tournament_registrations,
    ).where(
      tournament_registrations: { tournament_id: @tournament.id },
    ).where(id: all_players.map(&:id))
  end

  def import
    @import = Tournament::Import.new tournament_import_params
    if @import.save
      redirect_to tournaments_path, notice: "Imported tournament successfully"
    else
      @tournaments = Tournament.order(created_at: :desc)
      render action: :index, notice: "There were errors with your CSV file"
    end
  end

  private

  def tournament_params
    params.require(:tournament).permit(
      :name,
      :location,
      :begin_date,
      :end_date,
      :number_of_rounds,
    )
  end

  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def tournament_import_params
    params.require(:tournament_import).permit(:file)
  end
end

app/views/tournaments/_form.html.slim
#tournaments-new.container.row
  .col.s12.z-depth-4.card-panel
    .row
      .input-field.col.s12.center
        p.center.tournaments-new-form-text
        h2
          span New Tournament:
        h5
          span Tournament Director:
          = current_user.full_name

    = form_for @tournament do |f|
      .row.margin
        = render "shared/alerts", object: @tournament
      .row.margin
        .input-field.col.s12
          = f.label :name, class: "center-align", autofocus: true
          = f.text_field :name
      .row.margin
        .input-field.col.s12
          = f.label :location
          = f.text_field :location

      .row.margin
        .input-field.col.s4
          = f.label :begin_date
          = f.text_field :begin_date, class: "datepicker"
        .input-field.col.s4
          = f.label :end_date
          = f.text_field :end_date, class: "datepicker"
        .input-field.col.s4
          = f.label :number_of_rounds
          = f.number_field :number_of_rounds
      .row.margin
        button.btn.waves-effect.waves-light.col.s12 name="action" type="submit"
          = f.submit 'Save'

app/views/tournaments/_player.html.erb
<tr class="registered-player" id="<%= dom_id(player) %>">

  <td><%= player.full_name %></td>
  <td><%= player.rank %></td>
  <td><%= player.chapter_affiliation %></td>
  <td><%= player.first_name %></td>
  <td>
    <%= link_to update_tournament_registration_path(
      @tournament, player) do %>
      <i class="material-icons">edit</i>
    <% end %>
  </td>

</tr>

app/views/tournaments/_tournament.html.erb
<tr onclick="window.location='<%= tournament_path(tournament.id) %>';">
  <td><%= tournament.name %></td>
  <td><%= tournament.location %></td>
  <td><%= tournament.begin_date %></td>
  <td><%= tournament.end_date %></td>
</tr>

app/views/tournaments/index.html.erb
<div class="container">

  <h1>Tournaments</h1>
    <div class="card">
      <%= form_for @import, url: import_tournaments_path, multipart: true do |f|  %>
        <% if @import.errors.any? %>
        <div class="alert alert-error">
          <% @import.errors.full_messages.each do |msg| %>
            <div class="">
              <%= msg %>
            </div>
            <% end %>
        </div>
        <% end %>
        <%= f.file_field :file %>
        <%= f.submit "Upload Tournament from CSV", class: "btn btn lrg col s12" %>
      <% end %>
    </div>
  <table class="highlight">
    <thead>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Begin Date</th>
        <th>End Date</th>
      </tr>
    </thead>

    <tbody>
      <%= render @tournaments %>
    </tbody>
  </table>
</div>

app/views/tournaments/new.html.slim
= render "form"

app/views/tournaments/show.html.erb
<div class="container">
  <div class="row">
    <div class="card-panel grey lighten-1 z-depth-4">
      <h3 class="center-align truncate"><%= @tournament.name %> </h3>
      <h4 class="center-align">Tournament</h4>
      <h6 class="right-align">Location: <%= @tournament.location %></h6>
      <h6 class="right-align">Start Date: <%= @tournament.begin_date %></h6>
    </div>

  </div>
  <div class="row">

    <div class="col s6">
      <a class='dropdown-button btn col s12' href='#' data-activates='dropdown1'>Go to Round</a>
      <ul id='dropdown1' class='dropdown-content'>
        <% @tournament.rounds.each do |round| %>
        <li>
            <%= link_to "Round #{ round.number }", round_players_url(round) %>
        </li>

        <% end %>
      </ul>
    </div>
    <div class="col s6">
      <%= link_to "Standings", tournament_standings_path(@tournament), class: "btn waves-effect waves-light col s12" %>

    </div>
  </div>

  <div class="row">
    <div class="col s6">
      <div class="card-panel grey lighten-4 z-depth-4">
        <h4>Player Registration</h4>
        <%= render "tournament_registrations/form" %>
      </div>
    </div>
    <div class="col s6">
      <div class="card-panel grey lighten-4 z-depth-4">

        <h5 class="left-align"> <%= @tournament.players.count %> Registered Players</h5>

        <table class="highlight bordered">

          <thead>
            <tr>
              <th>Name</th>
              <th>Rank</th>
              <th>Club</th>
              <th>Reg. Status</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody id="registered-players">
            <%= render @players %>
          </tbody>

        </table>
      </div>
    </div>
  </div>
</div>