config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  resources :tournaments, only: %i[index new create edit show update destroy] do
    collection do
      post :import
    end
    resources :rounds, only: %i[index show create destroy]
    resources :players, only: %i[index update destroy]
  end
  resources :rounds do
    resources :players do
      get :pair, on: :collection
    end
    resources :games
  end
  resources :players do
    member do
      get :round_status
    end
    resources :games
  end
  resources :results, only: %i[update]

  resources :tournament_registrations, only: %i[create update]

  get "tournaments/:tournament_id/standings",
  to: "standings#index", as: :tournament_standings
end

app/views/shared/_alerts.html.slim
- flash.each do |message_type, message|
  = javascript_tag "Materialize.toast('#{message}', 4000)"

app/views/shared/_navbar.html.slim
nav.container
  .nav-wrapper.row.grey
    .col.s12
      .left.brandlogo
        h5 GO TOURNAMENT MANAGER

      - if current_user
        ul.right
          li
            = current_user.email
          li
            = link_to "Sign-Out", destroy_user_session_path, method: :delete

      - else
        ul.right
          li
            = link_to "Log-In", new_user_session_path
          li
            = link_to "Register", new_user_registration_path

app/views/shared/_sidenav.html.erb
    <ul id="slide-out" class="side-nav fixed">

      <li class="no-padding">
        <ul class="collapsible collapsible-accordion">

          <li class="bold">
            <a class="collapsible-header waves-effect waves-amber ">Tournaments</a>
            <div class="collapsible-body">
              <ul>
                <li><%= link_to "Select from Listing", tournaments_path %></li>
                <li><%= link_to "New", new_tournament_path %></li>

              </ul>
            </div>
          </li>
          <li class="bold">
            <a class="collapsible-header">Players</a>
            <div class="collapsible-body">
              <ul>
                <li><%= link_to "New", "#!" %></li>
              </ul>
            </div>
          </li>
          <li class="bold">
            <a class="collapsible-header">Games</a>
            <div class="collapsible-body">
              <ul>
                <li><%= link_to "Round 1", href="#!" %></li>
                <li><a href="#!">Round 2</a></li>
                <li><a href="#!">Round 3</a></li>
                <li><a href="#!">Round 4</a></li>
              </ul>
            </div>
          </li>
          <li class="bold">
            <a class="collapsible-header">Reports</a>
            <div class="collapsible-body">
              <ul>
              </ul>
            </div>
          </li>

        </ul>
      </li>
    </ul>
    <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>

app/views/shared/_tournament_side_nav.html.erb
<li class="bold">
  <a class="collapsible-header waves-effect waves-amber "><%= @tournament.name.truncate(20) %></a>
  <div class="collapsible-body">
    <ul>
      <li><%= link_to "Standings", tournament_standings_path(@tournament) %></li>


    </ul>
  </div>
</li>