config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  resources :tournaments, only: %i[index new create edit show update destroy] do
    collection do
      post :import
    end
    resources :rounds, only: %i[index show create destroy]
    resources :players, only: %i[index update destroy]
  end
  resources :rounds do
    resources :players do
      get :pair, on: :collection
    end
    resources :games
  end
  resources :players do
    member do
      get :round_status
    end
    resources :games
  end
  resources :results, only: %i[update]

  resources :tournament_registrations, only: %i[create update]

  get "tournaments/:tournament_id/standings",
  to: "standings#index", as: :tournament_standings
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                  :integer          not null, primary key
#  first_name          :string           not null
#  last_name           :string           not null
#  rank                :string           not null
#  aga_number          :string           not null
#  membership_exp_date :date             not null
#  rating              :decimal(, )      not null
#  chapter_affiliation :string           not null
#  state               :string           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Player < ApplicationRecord
  has_many :tournament_registrations
  has_many :tournaments, through: :tournament_registrations
  has_many :round_statuses
  has_many :rounds, through: :round_statuses
  accepts_nested_attributes_for :round_statuses
  accepts_nested_attributes_for :tournament_registrations
  attr_accessor :tournament_points, :previous_opponents
  validates_uniqueness_of :email
  validates_uniqueness_of :aga_number
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :aga_number, presence: true
  validates :email, presence: true
  validates :rank, presence: true
  validates :rating, presence: true
  default_scope { order("rating DESC") }
  scope :standings, -> { attr_accessor("tournament_points DESC") }
  alias_attribute :club, :chapter_affiliation

  def self.with_final_registration_statuses(tournament)
    Player.joins(:tournament_registrations).where(
      tournament_registrations: {
        tournament_id: tournament.id,
        status: "final",
      },
    )
  end

  def self.sorted_by_rating
    players = Players.all
    players.sort_by(&:rating)
  end

  def full_name
    first_name.upcase + " " + last_name.upcase
  end

  def games
    Game.where("white_player_id = ? OR black_player_id = ?", id, id)
  end
end

app/controllers/players_controller.rb
require "pairing_tool"
class PlayersController < ApplicationController
  def index
    @round = Round.find(params[:round_id])

    @tournament = @round.tournament
    @active_players = @round.players
    @rounds = @tournament.rounds

    @games = @round.games
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to @player, notice: "Added player"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @player.update(player_params)
      redirect_to @player, notice: "Updated player"
    else
      render :edit
    end
  end

  def pair
    @round = Round.find(params[:round_id])
    @tournament = @round.tournament
    @players = @round.players
    pairings = PairingTool.new(
      players: @players, tournament: @tournament, round: @round,
    ).execute
    @games = []
    pairings.each_with_index do |pairing, i|
      @games << if pairing[0].rating > pairing[1].rating
                  Game.create!(
                    round_id: @round.id,
                    white_player_id: pairing[0].id,
                    black_player_id: pairing[1].id,
                    table_number: i + 1,
                  )
                else
                  Game.create!(
                    round_id: @round.id,
                    white_player_id: pairing[1].id,
                    black_player_id: pairing[0].id,
                    table_number: i + 1,
                  )

                end
    end
    redirect_to round_players_path(@round),
       notice: "Game Pairings Created for Round  #{@round.number}"

    # if @games.each(&:save)
    #   redirect_to round_players_url,
    #    notice: "Game Pairings Created for Round  #{@round.number + 1}"
    # else
    #   render :index, notice: "There was an error"
    # end
  end

  private

  def player_params
    params.require(:player).permit(
      :first_name,
      :last_name,
      :rank,
      :aga_number,
      :membership_exp_date,
      :rating,
      :chapter_affiliation,
      :state,
      tournament_registrations_attributes: %i[id status tournament_id],
      round_statuses_attributes: %i[id status round_id],
    )
  end
end

app/views/players/_active_player.html.erb
<tr>
  <td><%= player.full_name %></td>
  <td><%= player.rank %></td>
  <td><%= player.club %></td>
</tr>

app/views/players/_active_players.html.erb
<tr>
  <td><%= player.name %></td>
  <td><%= player.rank %></td>
  <td><%= player.club %></td>
</tr>

app/views/players/_form.html.slim
#players-new
    .row
      .col.s12.center
    = form_for @player, url: tournament_registration_path(tournament_id: @tournament.id) do |f|
      .row.margin
        .input-field.col.s4
          = f.label :first_name, autofocus: true
          = f.text_field :first_name
        .input-field.col.s4
          = f.label :last_name
          = f.text_field :last_name
        .input-field.col.s4
          = f.label :rank
          = f.text_field :rank
      .row.margin
        .input-field.col.s3
          = f.label :aga_number
          = f.text_field :aga_number
        .input-field.col.s3
          = f.label :rating
          = f.text_field :rating
        .input-field.col.s3
          = f.label :club
          = f.text_field :chapter_affiliation
        .input-field.col.s3
          = f.label :state
          = f.text_field :state
      .row.margin
        .input-field.col.s4
          h6 Status:
          = select_tag("tournament_registration_status", options_for_select(preliminary: "preliminary", final: "final" ))


      .row.margin
        .col.s12
          h6 Active in:
          - @tournament.rounds.each do |r|
            .col.s3
              = check_box_tag "round_statuses[#{ r.number }]", "active", true
              = label_tag "round_statuses[#{ r.number }]", "Round #{ r.number }"

      .row.margin
        button.btn.waves-effect.waves-light.col.s12 name="action" type="submit"
          = f.submit 'Save'

app/views/players/_game.html.erb
<tr id="game-id">

  <td><%= game.table_number %></td>
  <td><%= game.white_player.full_name %>, <%=  game.white_player.rank %></td>
  <td><%= game.black_player.full_name %>, <%= game.black_player.rank %></td>
  <td><%= game.handicap %></td>

</tr>

app/views/players/_player.html.erb
<tr>

  <td><%= player.full_name %></td>
  <td><%= player.rank %></td>
  <td><%= player.chapter_affiliation %></td>
  <td><%= registration_status(@tournament, player) %></td>
  <td>
    <%= link_to tournament_path(@tournament, player_id: player.id) do %>
    <i class="material-icons">edit</i>
  <% end %>
</td>

</tr>

app/views/players/index.html.erb
<div class="container">

  <div class="row s12">
    <!-- Dropdown Trigger -->
    <a class='dropdown-button btn col s4' href='#' data-activates='dropdown1'>Select Round</a>

<!-- Dropdown Structure -->
    <ul id='dropdown1' class='dropdown-content'>
      <% @rounds.each do |round| %>
      <li>
          <%= link_to "Round #{ round.number }", round_players_url(round) %>
      </li>

      <% end %>
    </ul>
    <div class="col s4">

    </div>
    <div class="col s4">
      <%= link_to "Enter Game Results", round_games_path(@round), class: "btn waves-effect wvaes-light" %>

    </div>


  </div>
  <div class="col s12">
    <button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to "Pair Games", pair_round_players_path(@round) %>
  <i class="material-icons right">send</i>
</button>

  </div>
  <div class="row col s12">
    <div class="col s3">
      <table class="highlight bordered">
        <h1>Players</h1>
        <thead>
          <tr>
            <th>Name</th>
            <th>Rank</th>
            <th>Club</th>
          </tr>
        </thead>
        <tbody id="active-players">
          <% @active_players.each do |player| %>
            <%= render partial: "active_player", locals: { player: player } %>
          <% end %>
        </tbody>

      </table>
    </div>
    <div class="col s2">


    </div>
    <div class="col s7">
      <table class="bordered">
        <h1>Games</h1>
        <thead>
          <tr>
            <th>Table</th>
            <th>White</th>
            <th>Black</th>
            <th>Handicap</th>
          </tr>
        </thead>
        <tbody id="active-players">
          <% @games.each do |game| %>
            <%= render partial: "game", locals: { game: game } %>
          <% end %>
        </tbody>

      </table>
    </div>

  </div>
</div>

app/views/players/new.html.erb
<div class="container">
  <%= render "form" %>
</div>